version: "3"

services:
  db:
    image: postgres:12
    container_name: brbatel-postgres
    restart: always
    ports:
      - 127.0.0.1:${DB_PORT}:5432
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
  
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: brbatel-api
    volumes: 
      - .:/var/www/html
    ports: 
      - 127.0.0.1:${PORT}:3333
    environment: 
      CHOKIDAR_USEPOLLING: "true"
      DB_HOST: brbatel-postgres
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_PORT: ${DB_PORT}
      PORT: ${PORT}
    depends_on: 
      - db
    links: 
      - db