version: "3"

services:
  db:
    image: postgres:12
    container_name: brbatel-postgres
    restart: always
    ports:
      - 127.0.0.1:5432:5432
    environment:
      - POSTGRES_PASSWORD=brbatel
      - POSTGRES_DB=brbatel
      