version: "3"

services:
  db:
    image: postgres:12
    container_name: brbatel-postgres
    restart: always
    ports:
      - 127.0.0.1:${DB_PORT}:5432
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      