POST http://localhost:3333/companies HTTP/1.1
content-type: application/json

{
  "name": "Floraí",
	"cnpj": "00077877477789",
	"demand": 108000,
	"about": "Rede de supermercados",
	"annual_billing_id": "66555b30-2dc0-478d-a18f-246d948553d8"
}