PUT http://localhost:3333/companies/ba1ed8c7-79f0-47df-b20b-19d4b0c787b0 HTTP/1.1
content-type: application/json

{
  "name": "Açaí e Sorvete do Zé",
	"demand": 22000,
	"about": "Comércio de Açaí e Sorvetes"
}
